### PR TITLE
Fix signup prompt

### LINKED ISSUE #186: UX: Don't prompt for sign up if a private key exists
_From [j...@google.com](https://code.google.com/u/115532242577120581270/) on September 19, 2014 12:56:04_

  
**Steps to reproduce:**  
1\. Setup the extension and generate a key pair within the extension (or import one).  
2\. Go the options.  
  
**What happens?**  
You will see the option "Sign up to receive secret messages".  
  
**What do you expect to happen instead?**  
  
1\. The UI is misleading here if the user already has a private key in the key chain.  
  
Ideas:  
a) Do not show the "Sign up to receive secret messages" form at all and make it visible only on request (e.g. expand view) OR  
b) Change the wording to reflect that the user might already have a key set up below and should check that before creating another one  
  
2\. When the user enters the same email address again, a second list pair of priv/pub keys is shown underneath the already existing key with the same key ID's (i.e. no new key pair was generated, but the UI now shows a duplicate).  

_Original issue:_ <http://code.google.com/p/end-to-end/issues/detail?id=149>

### PR DESCRIPTION
**Pull request by taravancil**
Checks if the keyring has private keys, and only prompts the user to sign up if there are no private keys or the user clicks the prompt to generate another set of keys.

Resolves #186

### CODE REVIEW

File: src/javascript/crypto/e2e/extension/ui/settings/settings.js [hunk 1]
```diff
@@ -222,7 +263,7 @@ ui.Settings.prototype.removeKey_ = function(keyUid) {
 
 /**
  * Exports a PGP key.
- * @param {string} keyUid The ID of the key to export.
+ * @param {string} keyUid Tjhe ID of the key to export.
```
Comment (koto) [inline src/javascript/crypto/e2e/extension/ui/settings/settings.js]: Typo.

**Comment by adhintz** [comment]
Thanks for the code! Tested internally and it passes tests for me. Tested externally and it builds and looks good.
